Console.WriteLine("Введите x1");
int x1 = int.Parse(Console.ReadLine());
Console.WriteLine("Введите y1");
int y1 = int.Parse(Console.ReadLine());
Console.WriteLine("Введите z1");
int z1 = int.Parse(Console.ReadLine());
Console.WriteLine("Введите x2");
int x2 = int.Parse(Console.ReadLine());
Console.WriteLine("Введите y2");
int y2 = int.Parse(Console.ReadLine());
Console.WriteLine("Введите z2");
int z2 = int.Parse(Console.ReadLine());
double a1 = Math.Pow(x2-x1,2);
double a2 = Math.Pow(y2-y1,2);
double a3 = Math.Pow(z2-z1,2);
double res = Math.Sqrt(a1+a2+a3);
Console.WriteLine(res);
